# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: teamoops
email:
description: >
  a team of l33t hax0rs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teamoops.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: teamoops

# Build settings
markdown: kramdown
